/*Given a string, WAM to return all its subsequences in an arraylist. A String is a subsequence of a given String that is generated by deleting some character of a given string without changing its order.
Input: abc
Output: a, b, c, ab, bc, ac, abc*/

import java.util.ArrayList;

public class subssequences {
        static ArrayList<String> getSSQ(String str){
                ArrayList<String> ans =new ArrayList<>();
                if (str.length()==0) {
                        ans.add("");
                        return ans;
                        
                }
                char curr =str.charAt(0);
                ArrayList<String> smallAns =getSSQ(str.substring(1));
                for(String ss:smallAns){
                        ans.add(ss);
                        ans.add(curr+ss);
                }
                return ans;
}public static void main(String[] args) {
       String str ="abc";
       for (String i : getSSQ(str)){
        System.out.println(i);
       }}

}